const LOAD_RESOURCES = {
	"MicrowavesMeltOre/emp.gd": {"load_type": "script", "onready": false},
	"MVFSShaderStyles/SimulationLayer.gd": {"load_type": "script", "onready": false},
	"VariatedBroadcasts/ConversationPlayer.gd": {"load_type": "script", "onready": false},
	"CrewHider/CrewFaceOnEnceladus.gd": {"load_type": "script", "onready": false},
	"CrewHider/RestricedCrewList.gd": {"load_type": "script", "onready": false},
	"RemoveRingLimits/Escape Veloity.gd": {"load_type": "script", "onready": false},
	"RemoveRingLimits/Leaving Rings.gd": {"load_type": "script", "onready": false},
	"RemoveRingLimits/ship-ctrl.gd": {"load_type": "script", "onready": false},
	"TurretOverrides/PDT.gd": {"load_type": "script", "onready": false},
	"RemoveWeaponGimbals/PDT.gd": {"load_type": "script", "onready": false},
	"ShowMarketValue/MineralMarket.tscn":{"load_type":"scene","original_path":"res://enceladus/MineralMarket.tscn","onready":false},
	"ScoopExtraReturnDialogue/DIALOG_SCOOP_RETURNING_1.tscn":{"load_type":"scene","original_path":"res://comms/conversation/subtrees/DIALOG_SCOOP_RETURNING_1.tscn","onready":false},
	"BetterTooltips/DoTradeIn.gd": {"load_type": "script", "onready": false},
	"BetterTooltips/SystemShipRepairUI.tscn":{"load_type":"scene","original_path":"res://comms/conversation/subtrees/DIALOG_SCOOP_RETURNING_1.tscn","onready":false},
	"AchievementEnabler/AchievementAbstract.gd": {"load_type": "script", "onready": false},
	"ExtendedCrewIdentificationLimits/AutopilotOverlay.gd": {"load_type": "script", "onready": false},
	"ArmTargetToAutopilot/DockingArm.gd": {"load_type": "script", "onready": false},
	"DisplayNegativeDepth/ship-ctrl.gd": {"load_type": "script", "onready": false},
	"ExtraOMSDisplays/OMS.gd": {"load_type": "script", "onready": false},
	"ExtraOMSDisplays/CurrentGame.gd": {"load_type": "script", "onready": false},
	"ExtraOMSDisplays/ship-ctrl.gd": {"load_type": "script", "onready": false},
	"ShowEquipmentReliability/Upgrades.gd": {"load_type": "script", "onready": false},
	"PilotsReduceAstrogationCalcTime/ship-ctrl.gd": {"load_type": "script", "onready": false},
	"ScoopAutoReturnProtocol/ship-ctrl.gd": {"load_type": "script", "onready": false},
	"DisablePilotAutoAdrenaline/ship-ctrl.gd": {"load_type": "script", "onready": false},
	"ToggleSystemsAtEnceladus/SystemList.gd": {"load_type": "script", "onready": false},
	"ToggleSystemsAtEnceladus/Tuning.gd": {"load_type": "script", "onready": false},
	"ToggleSystemsAtEnceladus/ship-ctrl.gd": {"load_type": "script", "onready": false},
	"MaxAstrogatorTrackingTime/CurrentGame.gd": {"load_type": "script", "onready": false},
	"DisableMaintDroneSanBUS/drone-plant.gd": {"load_type": "script", "onready": false},
	"TemperatureBasedThrust/thruster.gd": {"load_type": "script", "onready": false},
	"NaturalTimeSkip/CurrentGame.gd": {"load_type": "script", "onready": false},
	"AutoRepairs/Repairs.gd": {"load_type": "script", "onready": false},
	"StationTransferSpeed/TradingHub.gd": {"load_type": "script", "onready": false},
	"OCPVoyagerFix/ocp-209.tscn":{"load_type":"scene","original_path":"res://ships/ocp-209.tscn","onready":false,"config":{"id":"VelocityPlus","section":"VP_SHIPS","entry":"fix_voyager_MPU_in_OCP"}},
}
